### ISSUE TITLE
ffdb.py is not a library

### ISSUE THREAD

**Issue by nicola** [mozilla/fireplay-sublime#15]
There are several issues that raised during development on the fact that ffdb is not a library. It does very little more than `MozClient` that paul has implemented does.

Main issues with ffdb:
- not possible to run multiple connection at the same time
- prints lot of logs
- errors are not thrown but concluded with `sys.exit(1)`
- not up-to-date implementation, see my [issue](https://github.com/kripken/emscripten/issues/2567)

**Comment by nicola** [comment]
I will see whether I can just implement the few things that they abstract

**Comment by sole** [comment]
So how did you sort it out, did you just use the "raw" protocol? (that's what I understand you're doing in https://github.com/mozilla/fireplay-sublime/blob/master/fireplaylib/client.py)

**Comment by nicola** [comment]
Yes, it is the implementation of the client. I will eventually switch to @campd, but will eventually need some more documentation.
