### ISSUE TITLE
homogenise quote styles

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#21]
The code has `['single_quotes']` sometimes and `["double_quotes"]` other times. Sometimes even [in the same object declaration](https://github.com/mozilla/fireplay-sublime/blob/b9303ce1227cd41e843fdfa8b940ca1716571429/fireplay.py#L48).

This has to be using the same style everywhere. I'd advise that we use just single quotes since they add less noise to the code - for example in cases [such as this one](https://github.com/mozilla/fireplay-sublime/blob/b9303ce1227cd41e843fdfa8b940ca1716571429/fireplay.py#L64-L65).

**Comment by nicola** [comment]
Ha! This is due to different code from different authors. I will work on that.

**Comment by nicola** [comment]
Fixed 6f39f6d632c2d4e1f439a38228b756c808e65796
