### ISSUE TITLE
Space after semicolons

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#22]
Python is very enforcing of white space in general but there are still some places such as object definitions where spaces are missing after the semicolon, but not always. [This is ugly](https://github.com/mozilla/fireplay-sublime/blob/b9303ce1227cd41e843fdfa8b940ca1716571429/fireplay.py#L107).

**Comment by nicola** [comment]
All that has to be changed into a more open form (my way)

**Comment by nicola** [comment]
Fixed 6f39f6d632c2d4e1f439a38228b756c808e65796

**Comment by fwenzel** [comment]
In Python, you can run a linter that'll yell at you if you make such mistakes. Ask in #webdev what the kids use nowadays. flake8 maybe?

**Comment by nicola** [comment]
Oh nice! Thanks for this.—
Typed with hands
