### ISSUE TITLE
`i` is not an appropriate variable name

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#25]
The usage of `i` as variable name in [here](https://github.com/mozilla/fireplay-sublime/blob/b9303ce1227cd41e843fdfa8b940ca1716571429/fireplay.py#L94-L98) is confusing.

A better name would be `bytes`.

**Comment by nicola** [comment]
ffdb copying issue, thanks!

**Comment by nicola** [comment]
Fixed 6f39f6d632c2d4e1f439a38228b756c808e65796
