### ISSUE TITLE
do you "open" firefox or "connect" to firefox?

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#26]
The pop up menu in Sublime offers you two options to "open", either Firefox or Firefox OS.

If no Firefox is running, will it open a Firefox instance? If it won't maybe the string should say "Connect to"

**Comment by nicola** [comment]
Until #11 is not fixed, it is not possible to detect whether firefox is open or not. This is by the way discussed in #16.

**Comment by nicola** [comment]
So, just to answer your question, at the moment, you can only connect to it, please have a look at #16 that is decisive.
