### ISSUE TITLE
Use a linter on existing and future code

### ISSUE THREAD

**Issue by fwenzel** [mozilla/fireplay-sublime#32]
Python is a pretty strict language when it comes to coding styles (four-space indentation, line length, import order, etc.). Luckily, that makes it easy to lint.

Please run `flake8` over your code (now and before you commit in the future), that'll take care of most these issues!

**Comment by nicola** [comment]
The only thing I can't handle now is long strings, apart from that error, linted.
Long strings is now in @sole's #24
