### ISSUE TITLE
Don't generate JSON by hand

### ISSUE THREAD

**Issue by fwenzel** [mozilla/fireplay-sublime#37]
https://github.com/mozilla/fireplay-sublime/blob/master/fireplaylib/client.py#L98

This is... I think... JSON? Don't generate it by hand like that. Two things:
- use the `json` module

```
In [3]: json.dumps({'hello': 'world', 'blah': 12})
Out[3]: '{"blah": 12, "hello": "world"}'
```
- And don't build strings with a series of `+` operators. Strings are immutable in Python, so each of these operations will create a completely new string, then throw it away. Instead, use string interpolation. `'Hello %s' % name` or `'Hello {name}'.format(person=name)`.

**Comment by nicola** [comment]
This comes straight from ffdb porting: https://github.com/kripken/emscripten/blob/master/tools/ffdb.py#L137

Will get into that soon
