### ISSUE TITLE
"Start new Firefox OS instance" doesn't do anything?

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#55]
If I don't have any simulator running, the only option I get when I press shift+cmd+R is a "Start new Firefox OS instance" but no matter how enthusiastically I click it, it doesn't do anything. Is this supposed to work like this or am I omitting something?

**Comment by nicola** [comment]
Ok you should (to do):
1. get an error message (bottom bar)
2. be asked to download firefoxOS instead!
