### ISSUE TITLE
Settings have various types of browsers hardcoded

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#56]
[Nightly, and non Nightly](https://github.com/mozilla/fireplay-sublime/blob/462167bf019db35c80c9ab4b62ca7e0bb1a7378f/fireplay.sublime-settings#L3-L5)

**Comment by nicola** [comment]
Ops, that was in my settings. I will switch that to Firefox, but how would you suggest me to move in that direction? Unless I find some cool feature in Mozrunner, one has to specify its path, if it is different from the main one.

**Comment by whimboo** [comment]
We tried to do some auto-detection of Firefox in the past but we dropped that because it's nearly impossible. That's why we explicitly require the user to set the path when using mozrunner.

**Comment by nicola** [comment]
Thanks for this clarification

**Comment by sole** [comment]
Could you "probe" the various official Firefoxes? Stable, Beta, Aurora and Nightly.

**Comment by nicola** [comment]
This is in mozrunner, I will remove hardcoded binaries I think—
Typed with hands
