### ISSUE TITLE
README improvements for clarity

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#57]
1. "In Sublime select Fireplay and follow the instruction" could be more specific. You can also just use cmd+shift+R
2. "Select to connect to existing Firefox or Firefox OS" - it doesn't work like that actually
3. "In your Sublime Text's packages folder, in fireplay.sublime-settings set fireplay_firefox to true" sounds confusing
4. Can fireplay.sublime-settings be renamed to have a .json at the end?
5. Once you've done the above... how do you use this? There's no mention to opening a project with an app source code, or no mention that when you save some files the app will be repushed. How do you see the console logs too?

**Comment by nicola** [comment]
1. OK
2. OK
3. Why does that sound confusing? I am improving it now! OK
4. Well we could, but that wouldn't be a standard practice (SKIP)
5. OK, console is not bound yet.
