### ISSUE TITLE
Crash when trying to bring up Fireplay

### ISSUE THREAD

**Issue by sole** [mozilla/fireplay-sublime#66]
I checked out the code https://github.com/mozilla/fireplay-sublime/tree/cbe4602d1764e09e213ad9781b6420186eab6e0a and now the plugin won't even start when I press cmd+shift+R as per the instructions.

If I open Sublime Text console I get this log:

``` bash
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./fireplay.py", line 384, in run
  File "./fireplaylib/b2g_helper.py", line 37, in find_b2gs
OSError: [Errno 2] No such file or directory: '/Users/sole/Library/Application Support/Firefox/Profiles/6ubqqf1n.default2-chrome-debugger/extensions'
```

My Firefox stable copy is just used for testing sites work, I don't have any extension installed-I use Firefox Nightly as my main browser.

**Comment by nicola** [comment]
Is this fixed?

**Comment by sole** [comment]
It is!
